- name: install mysql component
  hosts: mysql
  become: yes
  tasks:
  - name: Disable current mysql version
    ansible.builtin.command: yum module disable mysql -y
  
  - name: copy.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: install mysql-community-server
    ansible.builtin.yum:
      name: mysql-community-server
      state: installed

  - name: restart mysql
    ansible.builtin.service:
     name: mysqld
     state: restarted
     enbaled: true

  - name: setup mysql password
    ansible.builtin.command: mysql-secure-installation --set-root-pass Roboshop@1
